Add Meeting Mode
spoqa/slack-translator pull request #22
Opened 2018-03-29 06:35 UTC by qria

Adds meeting mode.

<img width="278" alt="screenshot at mar 29 15-34-50" src="https://user-images.githubusercontent.com/4233072/38073613-c30e569a-3366-11e8-8b91-8c9fa568845d.png">

2018-07-26 05:17 UTC, kanghyojun requested changes

2018-07-26 05:17 UTC, admire93 commented on app.py
> +        raise Exception('Please set `REDIS_URL` environment variable.')
`ValueError`정도면 괜찮을 거라고 생각합니다.

2018-07-26 05:17 UTC, admire93 commented on app.py
> +def load_from_redis(key):
```
+    if not redis_store:
+        raise Exception('Please set `REDIS_URL` environment variable.')
```
부분이 반복되는데 `store_to_redis`와 `load_from_redis`를 한클래스로 묶어서 `store` `load`라는 메서드로 정의하는게 더좋아보이긴합니다.

2018-07-26 05:22 UTC, qria commented on app.py
> +def load_from_redis(key):
@admire93 움 그러면 lazy evaluation이 어떻게 되는거죠? 이 기능 안쓰면 `REDIS_URL` 없어도 되는게 의도긴 했는데요..

2018-07-26 06:03 UTC, Kroisse commented on app.py
> +            'parse': 'full',
이 옵션이 사라진 것으로 보입니다. 확인이 필요할 것 같습니다.

https://api.slack.com/incoming-webhooks

2018-07-26 06:03 UTC, Kroisse commented on app.py
> +def detect_language(text):
좀 미묘하긴 하지만 대화하는 사용자의 지역 정보를 가지고 추측하는 것도 생각해볼 수 있을 것 같네요.

2018-07-26 06:03 UTC, Kroisse commented on app.py
> +    japanese_score = sum(bool(re_japanese.match(c)) for c in text)
제안:

```pycon
>>> import re
>>> re_korean = re.compile('[가-힣ㄱ-ㅎ]')
>>> text = 'changed DI-3669 *일본 매장 부정 적립 알림 메일이 한국어로 발송됨*'
>>> re_korean.findall(text)
['일', '본', '매', '장', '부', '정', '적', '립', '알', '림', '메', '일', '이', '한', '국', '어', '로', '발', '송', '됨']
>>> len(re_korean.findall(text))
20
>>> sum(1 for _ in re_korean.finditer(text))
20
>>>
```


https://docs.python.org/3/library/re.html#re.finditer

2018-08-20 07:22 UTC, qria commented on app.py
> +def detect_language(text):
🤔 애매한 것 같은데 일단 넘기겠습니다.

2018-08-20 07:26 UTC, qria commented on app.py
> +def load_from_redis(key):
@admire93 이거요 어차피 위에서 `env['REDIS_URL']`부분이 있어서 어차피 `REDIS_URL`없으면 터지네요. 그냥 `redis_store`를 not nullable로 둘게요

2018-08-20 08:42 UTC, qria commented on app.py
> +            'parse': 'full',
아직 살아있슴다: https://api.slack.com/methods/chat.postMessage

2018-08-20 16:14 UTC, Kroisse approved these changes

2018-08-21 02:06 UTC, kanghyojun approved these changes
고생하셨습니다! ㅜㅜ

2018-08-21 04:49 UTC, qria commented
py2때문에 터지는데 py2 서포트 드랍하고 minimum runtime을 py3.6으로 올릴게요

2018-08-21 07:35 UTC, qria commented
travis가 forked PR에선 안돌아서 #23 에서 머지할게요

2018-08-21 07:35 UTC, closed without merging